### ISSUE TITLE
Competitive play?

### ISSUE THREAD

**Issue by MilesCranmer** [werner-duvaud/muzero-general#1]
Hi,

Thanks for making this, it looks really nice to use! I'm curious: are there any extra modifications I need to make to my game file for competitive play between two agents?

Cheers,
Miles

**Comment by werner-duvaud** [comment]
Hi,
Thank you,

The multiplayer mode is a work in progress. I forgot to put it in the coming soon features. We will commit the multiplayer mode soon (one or two weeks) with a board game example when it will be ready.

You can take a look at the pseudocode to get an idea of ​​the changes to be made.

We will detail how to adapt a multiplayer game once the implementation is done.
