### ISSUE TITLE
On Ubuntu, installation instruction fail if swig is not installed

### ISSUE THREAD

**Issue by stephanemagnenat** [werner-duvaud/muzero-general#106]
The file `requirements.txt` lists `box2d-py` whose building depends on the presence of `swig`, which is not installed by default on Ubuntu (tested on 20.04). Installing swig (with `sudo apt install swig`) solves the problem. It might be helpful to add a note to the README about this problem.

**Comment by werner-duvaud** [comment]
Thank you.
Finally, we considered that the repo should just allow muzero to be installed and that there was no point in encumbering the installation with game-specific dependencies. We removed box2D but added an error message with installation instructions.
