### ISSUE TITLE
How do I merge this with TensorTrade environment? 

### ISSUE THREAD

**Issue by spacewalkingninja** [werner-duvaud/muzero-general#11]
https://github.com/tensortrade-org/tensortrade
see this here
@notadamking what do you think?

**Comment by werner-duvaud** [comment]
Hi,

You can take inspiration from examples already set up like [cartpole](https://github.com/werner-duvaud/muzero-general/blob/master/games/cartpole.py). It will be very similar if TensorTrade is compatible with the [gym API](http://gym.openai.com/docs/), you only need to create a tensortrade file in the games folder.
