### ISSUE TITLE
Analysis of diagnose model (not a bug)

### ISSUE THREAD

**Issue by jamesliu** [werner-duvaud/muzero-general#110]
It is interesting to use diagnose model to analyze the difference between virtual trajectory info and real trajectory_info. However, It would be great if some explanations can be provided  to understand what the plot tells us.
For examples: what does it tell us for different prior root value between virtual and real trajectory here?
Virtual trajectory info
![virtual_Prior root value](https://user-images.githubusercontent.com/41763/104213733-7af18280-53eb-11eb-8b50-6c18e63b3da4.jpg)
Real trajectory info
![real_Prior root value](https://user-images.githubusercontent.com/41763/104213763-847aea80-53eb-11eb-9e18-f99379a5e693.jpg)

**Comment by jamesliu** [comment]
Different MCTS depth. Does it mean we need more training to make the depth as similar as possible?
![Virtual trajectory_MCTS depth](https://user-images.githubusercontent.com/41763/104214558-6e215e80-53ec-11eb-8dd7-98ce24946384.jpg)
![Real trajectory - MCTS depth](https://user-images.githubusercontent.com/41763/104214578-75486c80-53ec-11eb-8858-8d593e9c78db.jpg)

**Comment by werner-duvaud** [comment]
Diagnose model is designed as a debugging and research tool for the implementation. It is better to use the TensorBoard plots to train a model and improve the training phase.

I am using the MCTS visualization (example below) to adjust the exploration parameters.
![mcts](https://user-images.githubusercontent.com/40442230/107081462-03005780-67f3-11eb-8705-819c260ad056.png)


Comparing the real trajectory and the virtual one allows to see how much in the future the model can plan without deviating too much.
