### ISSUE TITLE
Has anyone succeeded on Atari?

### ISSUE THREAD

**Issue by Jason-ZhouZJ** [werner-duvaud/muzero-general#123]
I've tried many hyperparameter settings on breakout and MsPacman. It turns out the models often diverge very quickly (the loss increase to NaN). I am wondering is there someone who has been able to get this code work on any atari environment? 
<img width="839" alt="Screen Shot 2021-01-23 at 1 33 34 AM" src="https://user-images.githubusercontent.com/26615718/105524747-07b90c00-5d1b-11eb-8a70-e2368c8b4ab5.png">

**Comment by ahainaut** [comment]
Hi @Jason-ZhouZJ ,
Concerning Atari, it requires a lot of computational resources to get an agent with the same performance as the one reported in the paper. 
About your problem with the high loss, as mentioned in the issue above, you can try to decrease the `lr_init` parameter.
Hope this helps.

**Comment by werner-duvaud** [comment]
Related to https://github.com/werner-duvaud/muzero-general/issues/127
