### ISSUE TITLE
Question for NONDETERMINISTIC game

### ISSUE THREAD

**Issue by dbsxdbsx** [werner-duvaud/muzero-general#124]
As muzero implies that it is only suitable for deterministic game,  does it mean that using original muzero would produce worse result than that from classic model-free algo in nondeterministic game?

As far as I know, stochastic policy is better than deterministic policy in nondeterministic game (from book Reinforcement learning An introduction 2ed version), and muzero is just like a model-free stochastic policy if with only 1 step planning. So intuitively, muzero should perform at learst not worse than  model-free algo.  

If I am wrong, tell me plz.
By the way , I found a [paper ](https://openreview.net/pdf?id=QnzSSoqmAvB) which extend muzero to  nondeterministic game, hope it useful to add new feature for this project.

**Comment by ahainaut** [comment]
Hi @dbsxdbsx, to be honest I haven't tested Muzero on stochastic games yet, and this implementation have not incorporated elements that could treat stochastic games differently from deterministic games. I suggest you post your question on the [discord](https://discord.gg/GB2vwsF) you'll probably get more feedbacks about experiments on stochastic games with Muzero !
