### ISSUE TITLE
name '__file__' is not defined

### ISSUE THREAD

**Issue by 1rashiid** [werner-duvaud/muzero-general#125]
I want to run the Muzero code in Jupyter, but I got this error in this line:

os.listdir(os.path.dirname(os.path.realpath(__file__)) + "/games")

name '__file__' is not defined
It's the first time that I want to run the code and understand the implementation. 
Could you help me to solve that? thank you.

**Comment by ahainaut** [comment]
Hi @1rashiid,
The current version of the code works fine for me using  the file muzero.py or the notebook.ipynb on google colab. If you tried to launch the notebook.ipynb in Jupyter, I think the `__file__` variable is not defined in Jupyter so I suggest you launch this file from colab or just run the `muzero.py` file directly.
