### ISSUE TITLE
Loss increasing after resuming training from a checkpoint

### ISSUE THREAD

**Issue by SwiftGodDev** [werner-duvaud/muzero-general#126]
I started training a model for chess yesterday. The results were quite good. But when I resumed training today, the loss is increasing. How do I fix this?

**Comment by ahainaut** [comment]
Hi, the loss in reinforcement learning is not necessarily supposed to be strictly decreasing as in "classical" machine learning so I don't think we can conclude that there is an error only based on this information.
Did you also load a replay buffer with the `model.checkpoint` file ? If not, this could explain the sudden change of performance if that's what you observed.

**Comment by SwiftGodDev** [comment]
Yes I loaded the replay buffer along with the checkpoint.

**Comment by ahainaut** [comment]
@SwiftGodDev
Ok so with these informations, nothing suggests that it is related to the implementation. I recommend you to go on the [discord](https://discord.gg/GB2vwsF) to ask your question as you experienced this on a custom environment.
