### ISSUE TITLE
POMDP 

### ISSUE THREAD

**Issue by WenyuHan-LiNa** [werner-duvaud/muzero-general#130]
I want use Muzero as a baseline for my own environment which is inherited from openai.gym. However, based on the design, my environment is partial observation. May I know if Muzero could be used to solve POMDP or at least used as a POMDP baseline?

**Comment by ziofil** [comment]
Muzero should be able to work with any MDP, hence also partially-observable ones.

**Comment by werner-duvaud** [comment]
@WenyuHan-LiNa It seems to me that it is preferable to avoid being in the case of a POMDP, there is an option to stack the observations and return to the MDP case (used for turning Atari games into a MDP) if it works with your environment.

There has been discussions about the stochastic and POMDP cases in the [discord](https://discord.gg/GB2vwsF).

**Comment by JohnPPP** [comment]
Hi werner,

First of all, thank you for sharing your work! Highly appreciated!

I cannot join the discord channel. It says the invitation is not valid. What can I do?

Thank you,
João

**Comment by werner-duvaud** [comment]
Does this link work better : https://discord.gg/GB2vwsF ?

**Comment by JohnPPP** [comment]
It did! Thank you very much :)
