### ISSUE TITLE
DataParallel vs DistributedDataParallel

### ISSUE THREAD

**Issue by StrangeTcy** [werner-duvaud/muzero-general#133]
[Pytorch documentation](https://pytorch.org/docs/stable/notes/cuda.html#cuda-nn-ddp-instead) basically says that it's generally a good idea to prefer DistributedDataParallel instead of plain old DataParallel, but [`models.py`](https://github.com/werner-duvaud/muzero-general/blob/master/models.py) used just DataParallel.
Is there a particular reason for this?

On the other hand, `muzero.py` uses `ray` to manage distributed processing, and I'm currently not sure how that happens. But it seems to have `tune`, which supports DistributedDataParallel

**Comment by ahainaut** [comment]
Hi @StrangeTcy ,
You’re right, using DistributedDataParallel would be better but we found DataParallel more convenient as it required less integration and it avoids adding new parameters for parallelization in the configuration. We will try to integrate this feature when we have time but in the meantime PR's are always welcomed !
