### ISSUE TITLE
updating check-pointing for using learners outside MuZero

### ISSUE THREAD

**Issue by EngrStudent** [werner-duvaud/muzero-general#140]
The industrial revolution included the breakthrough of "interchangeable parts".  In machine learners we aren't there yet.  Many folks use "csv" because big blue companies won't make interchangeable file formats.

I think you should consider making MuZero to make models (at checkpoints) that are useful substantially outside the MuZero framework, by rephrasing checkpointing using torch.jit.save as described here.

https://stackoverflow.com/questions/59287728/saving-pytorch-model-with-no-access-to-model-class-code

**Comment by ahainaut** [comment]
Hi @EngrStudent ,

Although this topic is interesting and is worth the discussion, I don’t think it would be very useful compared to the current check-pointing method and we don’t plan to incorporate this type of change for now. In any case, PR’s are welcomed if someone finds this features to be useful !
