### ISSUE TITLE
Why did I train lunarlander so slowly？more than 1 hour used 1 gpu

### ISSUE THREAD

**Issue by Augustiu** [werner-duvaud/muzero-general#144]
Why did I train lunarlander so slowly？more than 1 hour used 1 gpu

**Comment by werner-duvaud** [comment]
Hi,
MuZero is model based. For a step, MuZero must evaluate a tree of future steps. Therefore it is better in sample efficiency compared to model free algorithms but it takes more wall clock time to train.
You can also speedup the training by doing the selfplay on the GPU too or reducing the number of simulations in the MCTS.
