### ISSUE TITLE
Stop Training

### ISSUE THREAD

**Issue by JohnPPP** [werner-duvaud/muzero-general#145]
Hi,

How are you stopping the training? I'm pressing ESC and Python identifies the keyboard interrupt.

However, sometimes it does not create a replay buffer. 

Wondering if I'm doing anything wrong here.

Thank you,
João

**Comment by ZetiMente** [comment]
Cltrl C is Interrupt for me. Safety of the replay buffer can't be guaranteed unless the code ends gracefully. Stopping the program by interrupt should only be done to prevent the code from executing. You should lower the number of training steps if you want a smaller run.

**Comment by JohnPPP** [comment]
Thank you Matthew.


Matthew ***@***.***> escreveu no dia quinta, 1/04/2021 à(s)
03:01:
