### ISSUE TITLE
Keeps crashing Ubuntu

### ISSUE THREAD

**Issue by EngrStudent** [werner-duvaud/muzero-general#146]
I expanded the scope (and complexity) of tic-tac-toe, and when I run it, about iteration 600, it crashes Ubuntu.  I'm trying to diagnose it, and I suspect that the workers are running out of RAM.  If I reduce the "num_workers" then it doesn't crash, but it also can't bootstrap.  I think there are decaying learning parameters that disappear before enough relevant games are in the store.  

Things I have attempted:
- reducing stacked observations
- reducing number of workers
- radically reducing replay buffer size and unroll steps
- reducing num_simulations

I can't share code here, sorry.  Any thoughts on places to go to not have it reboot my workstation?

**Comment by JohnPPP** [comment]
Hi,

What if you change the settings to update the model.checkpoint more often? I don't know how to do this, so I asked on Discord. Perhaps someone can help us out.

Then, you could self-play on the model to update the functions. Perhaps the learning parameters would not be lost in this case...

(Please keep in mind that I have no idea of what I am saying. This can be totally wrong!)

**Comment by theword** [comment]
If you can not share the code modifications you have made, I do not know how you expect anyone to help you. 

Running the code out of the box, I am able to run 16 workers on ubuntu 20.04.

You can examine your RAM usage by going to the ray dashboard or typing the `htop` command into the terminal.
