### ISSUE TITLE
TicTacZero test game manually output buggish?

### ISSUE THREAD

**Issue by fbondeaux** [werner-duvaud/muzero-general#147]
I was trying out this package and noticed incorrect rendering/calculations when playing this game manually:

env = muzero.Game()
env.reset()
env.render()
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Press enter to take a step 
Enter the row (1, 2 or 3) to play for the player 0: 2
Enter the column (1, 2 or 3) to play for the player 0: 3
Choice: 5

Action: Play row 2, column 3
Reward: 0
[[0 0 0]
 [0 0 1]
 [0 0 0]]

Press enter to take a step 
Enter the row (1, 2 or 3) to play for the player 1: 2
Enter the column (1, 2 or 3) to play for the player 1: 1
Choice: 3

Action: Play row 2, column 1
Reward: 0
[[ 0  0  0]
 [-1  0  1]
 [ 0  0  0]]

**Press enter to take a step 
Enter the row (1, 2 or 3) to play for the player 0: 1
Enter the column (1, 2 or 3) to play for the player 0: 3
Choice: 2

Action: Play row 1, column 3 
Reward: 0
[[ 0  0  0]
 [-1  0  1]
 [ 0  0  1]]**

We expect the following output:
**[[ 0  0  1]
 [-1  0  1]
 [ 0  0  0]]**

It seems that the render function output is not working properly perhaps by some kind of sort method?

**Comment by fbondeaux** [comment]
Actually does someone mind to have a closer look at this?

**Comment by ZetiMente** [comment]
The row is counted from the bottom. So Row 1 col 3 is the bottom right corner.

**Comment by fbondeaux** [comment]
Yeah I've just written another render function.
