### ISSUE TITLE
Average pooling after residual tower

### ISSUE THREAD

**Issue by fidel-schaposnik** [werner-duvaud/muzero-general#15]
Hi! Could you provide a reference for the average pooling layer inserted in the residual networks after the tower and before the value, reward and policy heads? Can't seem to find any sign of it in the papers...

**Comment by ahainaut** [comment]
Hi, you are right, we decided to add one average pooling layer to reduce the computation time in case the size of the hidden state was too large. In any case, fixing the parameters of the pooling (`self.pooling_size` and `self.pooling_stride`) to 1 won't modify the output of the tower.
