### ISSUE TITLE
Dimensionality issue in continuous action space

### ISSUE THREAD

**Issue by alik604** [werner-duvaud/muzero-general#165]
Thank you for your implementation. 

I am having trouble adapting the continuous "Pendulum-v0" example to "LunarLanderContinuous-v2"
The issue I have is that when I get into the[ `game.step()` in `pendulum.py`](https://github.com/werner-duvaud/muzero-general/blob/continuous/games/pendulum.py#L148), the action is a single floating point. I can't figure out how to make it into two floating points like [0.1234, 0.987]. 

Since I want LunarLander, `self.observation_shape` is changed to (1,1,8), and that works as intended. I tried changing [`self.action_space = [i for i in range(2)]`](https://github.com/werner-duvaud/muzero-general/blob/continuous/games/pendulum.py#L19), but does not do anything because it used to set `self.action_space_size` which is never used. 

In `models.py` if i change the 2 to a 4, in `self.prediction_policy_network = FullyConnectedNetwork(encoding_size, fc_policy_layers, 2)`, that it appears in `None.expand()` which is in `self_play.py`, we can do the following  

``` python
# policy_params was (1,2), not it's (1,4)

self.mu, self.sigma = policy_params[0][0], policy_params[0][1]
action1 = models.sample_action(self.mu, self.sigma).item()

self.mu, self.sigma = policy_params[0][2], policy_params[0][3] # added
action2 = models.sample_action(self.mu, self.sigma).item()

action = (action1, action2) # insane and doesnt work
self.children[action] = Node()
```

I'm wanting to use MuZero for a paper related to continuous control, but I have no ability to get past this point on my own :'(

**Comment by ahainaut** [comment]
Hello @alik604,
Thank you for your interest in the continuous version of the project. A new continuous version has just been pushed, and it includes environments with multidimensional action space. You can check it out at: [Continuous MuZero](https://github.com/werner-duvaud/muzero-general/tree/continuous)
