### ISSUE TITLE
Would it possible to write go game and chess game program?

### ISSUE THREAD

**Issue by leqingli2000** [werner-duvaud/muzero-general#166]

**Comment by ZetiMente** [comment]
Yes

**Comment by ahainaut** [comment]
Hi,
You can use the spiel wrapper merged in the master branch for these two games ! See[ https://github.com/werner-duvaud/muzero-general/blob/master/games/spiel.py](https://github.com/werner-duvaud/muzero-general/blob/master/games/spiel.py) for modifications.
