### ISSUE TITLE
Scrabble implementation - How to include Player's rack observation 

### ISSUE THREAD

**Issue by nicolasnijssen** [werner-duvaud/muzero-general#167]
I'm working on an implementation of Scrabble. 

The board state is represented by a matrix with shape 15×15×27 (26 letters +1 wildcard, value 0/1) 
and the rack state 7×27 (rack always contains 7 tiles, value 0/1). How can I include the player's rack into the observation ? 

Because the board and rack observation have different dimensions, it's not possible to concatenate these and use the concatenation as the "game" observation . However I'm having difficulties with finding the correct way to use the player's rack observation in the network. 

Where/How do I include the rack observation ?
Is there any example present in the repository, that makes use of player's hand of cards/tiles ?

**Comment by JohnPPP** [comment]
Hi,

I think you might have two solutions;

   - create a 15*16*27 array (assuming only 1 player rack,. 17 for 2 players and so on)
   - Create a 15*15*27 array for the rack and fill the remaining cells with zeroes. The neural networks will eventually "filter" the non relevant info. If you have more players you can use the same array. First line for first player, second for.. and so on. Full of zeroes elsewhere.

Sharing that I did both solutions in an env. Even thought it was not very big array, I found almost no difference in training.

Hope it helps

**Comment by ahainaut** [comment]
Closing this since @JohnPPP proposed a solution. Feel free to re open for any other suggestions.
