### ISSUE TITLE
Scaling of historical stacked observations

### ISSUE THREAD

**Issue by tuero** [werner-duvaud/muzero-general#178]
I'm not sure if this is a bug or not or maybe I am missing something. When a raw action `a~[0, n)` is sent to the dynamics network, the network will convert the raw action into a feature plane such that the values are `1/a` (which follows the paper):
```python
# models.py
# MuZeroResidualNetwork.dynamics() ...
action_one_hot = (
    action[:, :, None, None] * action_one_hot / self.action_space_size
)
```
If no stacked observations are being used, then the prediction network simply takes in the current state. If however `M` stacked observations are being used, then the previous `M` observations and actions are stacked and used as input the prediction network. Since we are stacking, the raw actions need to be converted to planes as done in the dynamics network. What isn't being done though is the action feature plan scaling:
```python
# self_play.py
# GameHistory.get_stacked_observations() ...
previous_observation = numpy.concatenate(
    (
        self.observation_history[past_observation_index],
        [
            numpy.ones_like(stacked_observations[0])
            * self.action_history[past_observation_index + 1]
        ],
    )
)
```
I believe the expected behaviour is that the action planes are to be scaled, and I think the wording from the paper suggests that this is the case. Thus, I believe the above code should be as such, assuming game history structs have the `action_space_size` as a member variable:
```python
# self_play.py
# GameHistory.get_stacked_observations() ...
previous_observation = numpy.concatenate(
    (
        self.observation_history[past_observation_index],
        [
            numpy.ones_like(stacked_observations[0])
            * self.action_history[past_observation_index + 1] / self.action_space_size
        ],
    )
)
```

**Comment by tuero** [comment]
I also believe there is a related issue with the representation function. The result of `get_stacked_observations` is a stack of observations + action planes. Each action plane has a tiled value `a` (and above I think it should be `a / num_action`). In any case, the representation function then will min/max scale each channel in the stacked observation: https://github.com/werner-duvaud/muzero-general/blob/master/models.py#L526. 

Wouldn't this cause every action channel in the stacked observation to just be a tile of all 0's? Since the action channel is a channel of the same value, `min_encoded_state - max_encoded_state = 0` for those action channels. I've attached a quick gist demo to show that if we have a plane of all the same values passed to the representation function, then that channel gets 0'd (as would be the case for action planes): https://gist.github.com/tuero/67c4e99a1547ad4101973a4a7dcd3623

**Comment by ahainaut** [comment]
Hello @tuero ,

Thank you for your interest in the project and for reporting this issue ! The commit 0c4c335d0492d48f7cb8979d479b2761b5d267fb should have fixed this issue.
