### ISSUE TITLE
Tensorflow support

### ISSUE THREAD

**Issue by jl1990** [werner-duvaud/muzero-general#18]
Hi,

I would like to ask if tensorflow will be supported also as per the initial README (https://github.com/werner-duvaud/muzero-general/commit/d8388353cd37242efcdb7ff36680fc7059ecff6c#diff-04c6e90faac2675aa89e2176d2eec7d8).

Thanks

**Comment by werner-duvaud** [comment]
Hi,

It is still in our roadmap but it is no longer a priority.
I cannot guarantee a date for this feature. We have a lot to do before, we are already improving the PyTorch version before adding TensorFlow.

However, any contribution is welcome.

**Comment by jl1990** [comment]
Thanks for the clarification!
