### ISSUE TITLE
Why my game does not remember the steps trained

### ISSUE THREAD

**Issue by hairinwind** [werner-duvaud/muzero-general#181]
I created my test game and trained it.
For example, I stopped at Training step: 5000/10000
Next time, I select "load the pretrained model" then select "train". It starts from 0/10000. Why it does not remember the 5000 steps already trained?

Thanks!!!

**Comment by hairinwind** [comment]
I basically knew the reason why it happened. 
One scenario is that I press ctrl + C more than once, and the pickle.dump() is not executed and the replay_buffer.pkl is not saved. 
The other scenario is that some errors happen, for example, gpu out of memory, the replay_buffer.pkl is not saved. 

Now my question is if the replay_buffer.pkl is not saved, is it still ok to load the model and continue the training? 

Thanks,

**Comment by ahainaut** [comment]
Hello,
It is possible to load the model without the replay buffer and continue the training. Of course it is generally better to already have a replay buffer to continue the training.

**Comment by ahainaut** [comment]
Closing this since the initial question seems to have been answered but feel free to open a new issue if you had any other questions on this topic !
