### ISSUE TITLE
Training on ended games

### ISSUE THREAD

**Issue by manuel-delverme** [werner-duvaud/muzero-general#24]
https://github.com/werner-duvaud/muzero-general/blob/4d541626a2d1ace2e3bdf30d25d9a843e4cb613c/replay_buffer.py#L79

Shouldn't this be:
`position_probs = numpy.array(game_history.priorities[:-1]) / sum(game_history.priorities[:-1]) `

It makes no sense to learn from the last step because we would be training against illegal moves (and zero reward as per my last issue)

**Comment by werner-duvaud** [comment]
Hi,

I'm not sure I understand.
For me the last step is not an illegal move. It is the terminal state in which we received the last reward given by the game. So in my opinion it makes sense to train on it.

What issue are you referring to? The reward is zero and is ignored for the initial inference, I think it corresponds to the first step not to the last.
