### ISSUE TITLE
Graph Based Games

### ISSUE THREAD

**Issue by datavistics** [werner-duvaud/muzero-general#26]
How would I go about using this for a graph based game like risk?

**Comment by datavistics** [comment]
@werner-duvaud any advice?

**Comment by werner-duvaud** [comment]
Hi,

Indeed, I think it could be interesting to transform the networks into graph neural networks to work with graph data. You have to change the [models.py](https://github.com/werner-duvaud/muzero-general/blob/master/models.py) file.

About the risk game, for the moment MuZero is rather oriented for games with 2 players who play in turn.

**Comment by mfogelson** [comment]
@datavistics did you ever implement an example with a GCN ?
