### ISSUE TITLE
OutofMemoryError: Actors use too much memory

### ISSUE THREAD

**Issue by AasheeshT** [werner-duvaud/muzero-general#32]
Cheers for the wonderful code! I am using it for atari game. But the worker threads use too much memory resulting in out of memory error.

RayTaskError(RayOutOfMemoryError): ray::SharedStorage (pid=2986, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 431, in ray._raylet.execute_task
  File "/usr/local/lib/python3.6/dist-packages/ray/memory_monitor.py", line 120, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node 8ff9db8651eb is used (12.13 / 12.72 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
3039	4.53GiB	ray::SelfPlay.continuous_self_play()
3054	4.5GiB	ray::SelfPlay.continuous_self_play()
2985	1.26GiB	ray::Trainer.continuous_update_weights()
126	0.38GiB	/usr/bin/python3 -m ipykernel_launcher -f /root/.local/share/jupyter/runtime/kernel-4404f6dc-8f78-4a
2986	0.14GiB	ray::SharedStorage
3026	0.08GiB	ray::ReplayBuffer
2966	0.08GiB	/usr/bin/python3 -u /usr/local/lib/python3.6/dist-packages/ray/dashboard/dashboard.py --host=localho
26	0.07GiB	/usr/bin/python2 /usr/local/bin/jupyter-notebook --ip="172.28.0.2" --port=9000 --FileContentsManager
2960	0.04GiB	/usr/local/lib/python3.6/dist-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *:44319
3048	0.04GiB	ray::IDLE

In addition, up to 0.24 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.

**Comment by werner-duvaud** [comment]
Hi,

Thank you

Indeed, I see that it uses more than 12 GB of Ram which is the limit of your computer.
There are two things:
First of all, compatibility with Atari games is a work in progress. You can see in the paper appendix Network Architecture that the DeepMind team is reducing the size of the observations. We haven't committed this yet. It will reduce memory usage.

In the meantime, you can on your side reduce the resolution, lower the number of actors and use networks with fewer parameters.

However, note that training RL agents on Atari generally requires very good computers.
