### ISSUE TITLE
Question about ucb_score

### ISSUE THREAD

**Issue by JoshVarty** [werner-duvaud/muzero-general#33]
I have a question about the calculation of [`ucb_score`](https://github.com/werner-duvaud/muzero-general/blob/b94cd65b91f3e185f0f206269446eefe9152c28b/self_play.py#L320-L342
).
In particular `value_score` is calculated as: 

```Python
value_score = min_max_stats.normalize( 
                 child.reward + self.config.discount * child.value() 
             ) 
```

In two player games like Tic-Tac-Toe the players alternate turns. The value of a given state for me is the exact negative of the value of a given state for my opponent. I see this is represented in `backpropagate()`: 

https://github.com/werner-duvaud/muzero-general/blob/b94cd65b91f3e185f0f206269446eefe9152c28b/self_play.py#L350

My question is: Doesn't this information need to be taken into account when calculating `ucb_score`? That is, don't we have to negate the value of `child.value()` since the child is a state from the perspective of our opponent?

For that matter, I see `expand` always uses the unmodified `reward` from `recurrent_inference` but `backpropagate` negates the `value` depending on the value of `virtual_to_play`?

Can you help me better understand how this works in muzero?

**Comment by werner-duvaud** [comment]
Hi,

If I understood correctly what you are suggesting, I think this is in fact what is being done.

When we call [`child.value()` in the `ucb_score`](https://github.com/werner-duvaud/muzero-general/blob/b94cd65b91f3e185f0f206269446eefe9152c28b/self_play.py#L337), we call the [`Node.value()`](https://github.com/werner-duvaud/muzero-general/blob/b94cd65b91f3e185f0f206269446eefe9152c28b/self_play.py#L370) function which depends on `self.value_sum` which itself is updated by : https://github.com/werner-duvaud/muzero-general/blob/b94cd65b91f3e185f0f206269446eefe9152c28b/self_play.py#L350

So we have taken into account the different players in `child.value()`.

For me, the reward and value stored in each node of the MCTS is from the perspective of that node.
Then we use the ucb_score to favor the exploration of good moves for the player and good moves of the opponent by taking each time the action maximizing the ucb score regardless of the player.
