### ISSUE TITLE
Last edit broke something?

### ISSUE THREAD

**Issue by Diapa** [werner-duvaud/muzero-general#34]
When I run a freshly cloned version of this program to train connect4, all graphs in the Total_reward-section of tensorboard become flat lines (Total reward=10, Mean value=0, Episode length=11, MuZero reward=0, Opponent reward=0). The graphs in all of the other sections look ok I think. I get this result both locally and in Google colab.

It worked before https://github.com/werner-duvaud/muzero-general/commit/91afb1d7b77f5c9382ac3651d9d139cded895a63 so maybe something broke there?

**Comment by ahainaut** [comment]
Hi,

Thanks for reporting. It should be fixed now.
