### ISSUE TITLE
Connect 4 bug

### ISSUE THREAD

**Issue by guskal01** [werner-duvaud/muzero-general#37]
There is a bug in the connect 4 game logic, but it's small enough that I'm sure it hasn't affected training. If a player (parity says it must be player 2) wins on the last move of the game (move 42), it will be rewarded as a draw.
From connect4.py: `reward = 1 if done and 0 < len(self.legal_actions()) else 0`
No legal actions doesn't mean someone didn't just win.

Example:
```
a = self.Game()
mv = [2,1,1,1,3,1,4,1,6,5,7,2,3,4,5,6,7,7,6,5,4,3,2,7,6,5,4,3,2,2,3,4,5,6,7,7,6,5,4,3,2,1]
for m in mv:
    x = a.step(m-1)[1:]
    print(x)
    a.render()
```
Last step prints (0, True) even though the second player won. https://connect4.gamesolver.org/?pos=211131416572345677654327654322345677654321

**Comment by guskal01** [comment]
Same bug also present in tictactoe.

**Comment by werner-duvaud** [comment]
Thank you !

It should be good now.
