### ISSUE TITLE
Issue with image based environemts. 

### ISSUE THREAD

**Issue by hnekoeiq** [werner-duvaud/muzero-general#39]
Hi, thanks a lot for this well-organized code.

I tried your code for CartPole and it works fine. However, I cannot get any results with other environments (e.g Breakout) especially those with an image as input. In these cases, it repeats taking the same actions during all the episodes. Do you have any suggestions where should I start tunning some hyper-parameters?

**Comment by werner-duvaud** [comment]
Hi,

About the games you can't train:
With the fully connected network and the proposed hyperparameters we manage to solve gridworld optimally in 8000 self played games and 4000 training steps, it is easily reproducible. LunarLander is more complicated to train, removing the stochastic aspects except the initial random position of the ship helps a lot.

With the residual network, on tic tac toe we get almost 100% of victories by playing first against a random agent (15,000 self played games and 9,000 training steps). The winning ratio decreases at first (first 400 self played games) and then increases slowly but steadily.
Unfortunately we don't have the computing power to properly tune the hyperparameters of the other games.

Concerning the images, you should use the ResNet and you can use the downsample to reduce their size.

The repetition of the same action is often a sign of a lack of training, we have the same behavior at the beginning on gridworld for example. It can also be linked to poor exploration.

Regarding Atari, all the hyperparameters are in the paper of MuZero and the pseudocode (make_atari_config) and Alpha Zero. One million training steps with a batch of 1024, 350 simultaneous actors, 27000 max moves per game allowed. 256 planes in the ResNet with 16 blocks. It’s really a lot. I'm going to update the breakout configuration, it should be close to what DeepMind uses.
