### ISSUE TITLE
raise pickle.PicklingError(msg)

### ISSUE THREAD

**Issue by serenaTangarfff** [werner-duvaud/muzero-general#45]
When I trained the game, an error raised "raise pickle.PicklingError(msg)". Why raised this error ?

<img width="718" alt="raise pickle PicklingError(msg)" src="https://user-images.githubusercontent.com/53207897/81167886-58e06e80-8fd9-11ea-94ff-be67ae54916d.png">

**Comment by werner-duvaud** [comment]
Hi,

It seems you have reached the python maximum recursion depth with pickle. 

What game do you get this with?

Increasing the python recursion limit should solve your problem.
You can insert something like that at the begining of the actor python files:

```python
import sys
sys.setrecursionlimit(10000)
```

**Comment by serenaTangarfff** [comment]
@werner-duvaud Thanks. The problem has been solved.
