### ISSUE TITLE
Diagram cut off

### ISSUE THREAD

**Issue by AdrianAcala** [werner-duvaud/muzero-general#46]
The diagram at the bottom of the page in [How MuZero works](
https://github.com/werner-duvaud/muzero-general/wiki/How-MuZero-works) is cut off.

**Comment by werner-duvaud** [comment]
Hi,

In fact, the graph ends like this, it is not cut as you can see in the [image here](https://github.com/werner-duvaud/muzero-general/blob/master/docs/muzero-network-werner-duvaud.png). You're right, the gradient is confusing but the idea was to show that the dynamics and prediction blocks are repeated as many times as desired.

**Comment by AdrianAcala** [comment]
Got it thank you.
