### ISSUE TITLE
Place for communication?

### ISSUE THREAD

**Issue by AdrianAcala** [werner-duvaud/muzero-general#48]
Is there a slack, discord, discourse or other form for communicating about this project? I'd love to help contribute to this project but my skills aren't very good in ML. I was wondering if I could assist with a CI/CD system or help with creating a grid search for hyperparameter searching.

**Comment by werner-duvaud** [comment]
Hi,

Great idea, I just created a server discord [here](https://discord.gg/GB2vwsF).

Any help is welcome. I was also thinking of including tests but I haven't had time yet.
About hyperparameter searching, I'm using [this](https://github.com/werner-duvaud/muzero-general/blob/1d2d605aa07af82b4a7ddad308aa128fe076182d/muzero.py#L331) but it is clearly not the best way to do it.

**Comment by AdrianAcala** [comment]
Great. Thanks :-)
