### ISSUE TITLE
Question about "reward" values in new games

### ISSUE THREAD

**Issue by whyrv** [werner-duvaud/muzero-general#49]
For any new games which I could add, is there any min/max range for the reward to be followed? For the gym Atari games, I am not aware of any clipping.  

Specifically
`def step(self, action):

        observation, reward, done = self.env.step(action) #<--does this reward need to be in some range?
        return observation, reward, done
`
Thanks!

**Comment by AdrianAcala** [comment]
No min max range strictly. What were you thinking of?

**Comment by whyrv** [comment]
hi, thanks. openai range for many game is (-inf,inf) So just want to be sure that the code is not expecting this to be normalized or clipped to a range, before I try some.

**Comment by AdrianAcala** [comment]
Be aware, Python has a certain amount of precision in how it represents numbers for floats. If you use an integer, you should be fine.

```
>>> num = 123456789000000000000000 +1
>>> num - 123456789000000000000000
1L
>>> num = 123456789000000000000000.0 + 1
>>> num - 123456789000000000000000.0
0.0
```

We lost the 1 we had because

**Comment by AdrianAcala** [comment]
Pretty sure you're going to lose information because of the lack of precision. If you are adding really large numbers and really small numbers you're going to probably lose those small numbers because numpy uses C-style fixed-precision integers. 

I'd also let @werner-duvaud answer this as it may affect the loss function.

Python has arbitrary precision for integers but not for floats, but muzero uses numpy.

```
>>> num = 123456789000000000000000 +1
>>> num - 123456789000000000000000
1L
>>> num = 123456789000000000000000.0 + 1
>>> num - 123456789000000000000000.0
0.0
```

See: 
https://mortada.net/can-integer-operations-overflow-in-python.html

**Comment by whyrv** [comment]
thank you. I plan to be well within 32 bit integer range.

**Comment by ahainaut** [comment]
Hi, 

Concerning reward and value, we scale the target using the invertible transform :
![CodeCogsEqn](https://user-images.githubusercontent.com/59559236/81499617-1bc3f700-92cd-11ea-87ab-10d3c857c3e0.gif)

 and then we encode the scaled reward/value with a transform ![CodeCogsEqn-2](https://user-images.githubusercontent.com/59559236/81499641-431ac400-92cd-11ea-80b8-0f999b9c39b8.gif) (detail of the whole process in [Appendix F of MuZero paper](https://arxiv.org/pdf/1911.08265.pdf)). Therefore, the scaled reward/value range is determined by the support size. For example if support size is 300, the scaled reward will be in a range of [-300, 300]. Applying the invert scaling : 
![CodeCogsEqn-3](https://user-images.githubusercontent.com/59559236/81499788-524e4180-92ce-11ea-98f4-674dc4c14b13.gif)
 gives us a reward between -58705.6 and 58705.6 approximately 
However, this shouldn’t be a real issue as this whole process was applied by DeepMind on Atari games. 

You should also be careful of the range indicated in the [following chart](https://github.com/openai/gym/wiki/Table-of-environments). For example, in Cartpole-v0, reward is 1 for every step.
