### ISSUE TITLE
what the different between MuZero_reward and total reward?

### ISSUE THREAD

**Issue by serenaTangarfff** [werner-duvaud/muzero-general#51]
Hi,

In the Tensorboard for Tictactoe, I saw two diagrams abut reward,  MuZero_reward and total reward. What the different between MuZero_reward and total reward?

<img width="771" alt="屏幕快照 2020-05-13 下午5 36 32" src="https://user-images.githubusercontent.com/53207897/81784644-84ff7080-9540-11ea-9530-c6133a62032c.png">

**Comment by werner-duvaud** [comment]
Hi,

In single player games, `Total reward` is the sum of the reward per episode. `MuZero reward` and `Opponent reward` are disabled.

In multiplayer games, `MuZero reward` is the sum of the rewards obtained by Muzero and `Opponent reward` is the sum of the rewards of the opponent. `Total reward` is the sum of the two.

**Comment by serenaTangarfff** [comment]
@werner-duvaud thanks.
