### ISSUE TITLE
Alternating reward signs in backpropagate

### ISSUE THREAD

**Issue by fidel-schaposnik** [werner-duvaud/muzero-general#55]
In 

https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/self_play.py#L384

the value to be backpropagated along the search path incorporates rewards from all nodes with the same sign, which seems in contradiction with

https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/self_play.py#L380

and the way value targets are being computed in

https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/replay_buffer.py#L206

Is this intentional? Or maybe this line should be corrected to something like:

`value = node.reward + self.config.discount * value if node.to_play == to_play else -node.reward + self.config.discount * value`

**Comment by werner-duvaud** [comment]
I think you are right, thank you.
Fortunately it should not have a big impact on the games already implemented.
About the code you suggest to fix it, I would have rather done the opposite:

value = (-node.reward if node.to_play == to_play else node.reward) + self.config.discount * value

What do you think ?

**Comment by fidel-schaposnik** [comment]
Sure, shorter and clearer! I guess for 1-player games this is not an issue, and for 2-player games it mostly introduces some noise in the values, but it may be another reason training can be unstable...

**Comment by werner-duvaud** [comment]
Sorry it wasn't clear, I changed the reward sign when the condition is true where you suggested the opposite. It is just to check if it is a typo or maybe I missed something.

**Comment by fidel-schaposnik** [comment]
Oops, sorry I hadn't noticed that change! I think you are right, but let me just check I understand your logic:

- values should be considered to be relative to whoever is about to play (i.e. `to_play` variables)
- rewards should be considered to be relative to whoever has just played (let's say, `gets_reward = 1-to_play` for two-player games)

In `backpropagate` we have:

- `value` is relative to `to_play`
- `node.value` is relative to `node.to_play`
- `node.reward` is relative to `node.gets_reward = 1 - node.to_play`

We are updating `value`, so I'd go for:

`value = (node.reward if node.gets_reward == to_play else -node.reward) + self.config.discount * value`

**which is equivalent to what you suggested (and not my original proposal)**. Then the line

https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/self_play.py#L380

does the final adjustment to match whichever node we are updating. **Does all of this sound right?**

However, I'm now somewhat confused because I notice that in 

https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/replay_buffer.py#L236

we are essentially updating `game_history.root_values[bootstrap_index]`, which is relative to `game_history.to_play_history[bootstrap_index]`, but in line 

https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/replay_buffer.py#L238

you compare to `game_history.to_play_history[index]` and not `game_history.to_play_history[bootstrap_index]`. Of course, `game_history.to_play_history[bootstrap_index]` may not even exist at this point, so I guess the way to go here would be to first make `last_step_value` relative to `game_history.to_play_history[index]` changing

https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/replay_buffer.py#L227

to something like

`last_step_value = (1 if game_history.to_play_history[bootstrap_index] == game_history.to_play_history[index] else -1) * game_history.root_values[bootstrap_index] `

**Am I making any sense?**

Anyway, all of these details are pretty annoying... I'd much rather have absolute rewards and values (at the cost of slightly larger networks), but I'm guessing that the DeepMind team had a very good reason to do things this way... probably related to squeezing every last bit of efficiency from the MCTS routines.

**Comment by werner-duvaud** [comment]
I think you are completely right on both points. Thank you very much for the time you have spent.

**Comment by nemtiax** [comment]
For what it's worth, I ran into this same issue in my own implementation.  I arrived at a similar solution:

``if self.game.is_turn_taking():
                value_score = node.reward - self.discount * node.q_value()
            else:
                value_score = node.reward + self.discount * node.q_value()``

It seems like DeepMind's pseudocode just has a bug here.  They check for turn-taking and negate values elsewhere, but not in backpropogate.

**Comment by fidel-schaposnik** [comment]
You're welcome, and thanks for confirming I'm understanding things properly. I'll try to play with this implementation a bit later, maybe report back some results or suggest performance optimizations...

**Comment by werner-duvaud** [comment]
We are going to look at the whole code again, I think we didn't take into account the cases with two players where it predicts intermediate rewards. Thanks again

About the line you mentioned, l think 
`(child.reward if parent.to_play == child.to_play else -child.reward) + self.config.discount * child.value()`
 should fix it
