### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for MuZeroFullyConnectedNetwork

### ISSUE THREAD

**Issue by Huagela** [werner-duvaud/muzero-general#63]
Below all used dialogue from `python muzero.py`

I have trained a lunarlander model.
When load pretrained model, an error occurs:
`
RuntimeError: Error(s) in loading state_dict for MuZeroFullyConnectedNetwork:
	Missing key(s) in state_dict: "representation_network.0.weight", "representation_network.0.bias", "dynamics_encoded_state_network.0.weight", "dynamics_encoded_state_network.0.bias", "dynamics_encoded_state_network.2.weight", "dynamics_encoded_state_network.2.bias", "dynamics_reward_network.0.weight", "dynamics_reward_network.0.bias", "dynamics_reward_network.2.weight", "dynamics_reward_network.2.bias", "prediction_policy_network.0.weight", "prediction_policy_network.0.bias", "prediction_policy_network.2.weight", "prediction_policy_network.2.bias", "prediction_value_network.0.weight", "prediction_value_network.0.bias", "prediction_value_network.2.weight", "prediction_value_network.2.bias". 
	Unexpected key(s) in state_dict: "representation_network.layers.0.weight", "representation_network.layers.0.bias", "dynamics_encoded_state_network.layers.0.weight", "dynamics_encoded_state_network.layers.0.bias", "dynamics_encoded_state_network.layers.2.weight", "dynamics_encoded_state_network.layers.2.bias", "dynamics_reward_network.layers.0.weight", "dynamics_reward_network.layers.0.bias", "dynamics_reward_network.layers.2.weight", "dynamics_reward_network.layers.2.bias", "prediction_policy_network.layers.0.weight", "prediction_policy_network.layers.0.bias", "prediction_value_network.layers.0.weight", "prediction_value_network.layers.0.bias", "prediction_value_network.layers.2.weight", "prediction_value_network.layers.2.bias".
`

how can i fix it?  thx~

**Comment by werner-duvaud** [comment]
Hi,

This happens when you load weights that do not match the current game configuration.
I think you're loading the wrong weights.

* First check that you have changed self.save_weights = True in the configuration.
* Then load the weights in the results folder with the current date time.

**Comment by Huagela** [comment]
thx～ I followed the steps above, set `self.save_weights = True` and retrained my model. Then load the `model.weights` and  `replay_buffer.pkl`, render works!
