### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by yffbit** [werner-duvaud/muzero-general#66]
There seems to be a bug on Windows 10 with cuda devices. `torch.nn.DataParallel(model)` will move model parameters and buffers to the GPU even if `selfplay_device = 'cpu'`. If you move the model to cpu `model.to(torch.device('cpu'))` after the model is created, the inference process will raise a RuntimeError.

> 
    def __init__(self, module, device_ids=None, output_device=None, dim=0):
        super(DataParallel, self).__init__()

        if not torch.cuda.is_available():
            self.module = module
            self.device_ids = []
            return

        if device_ids is None:
            device_ids = list(range(torch.cuda.device_count()))
        if output_device is None:
            output_device = device_ids[0]

        self.dim = dim
        self.module = module
        self.device_ids = list(map(lambda x: _get_device_index(x, True), device_ids))
        self.output_device = _get_device_index(output_device, True)
        self.src_device_obj = torch.device("cuda:{}".format(self.device_ids[0]))

        _check_balance(self.device_ids)

        if len(self.device_ids) == 1:
            self.module.cuda(device_ids[0])

    def forward(self, *inputs, **kwargs):
        if not self.device_ids:
            return self.module(*inputs, **kwargs)

        for t in chain(self.module.parameters(), self.module.buffers()):
            if t.device != self.src_device_obj:
                raise RuntimeError("module must have its parameters and buffers "
                                   "on device {} (device_ids[0]) but found one of "
                                   "them on device: {}".format(self.src_device_obj, t.device))

It means DataParallel model can only run on cuda if cuda is available. Similar issue [https://discuss.pytorch.org/t/does-dataparallel-matters-in-cpu-mode/7587](url)

**Comment by werner-duvaud** [comment]
The code has been tested with GPUs on ubuntu and without GPU on macOS, the selfplay seems to be on the right device.
What you describe should not happen because we are using Ray to manage the visible GPUs, so if you set `selfplay_device = 'cpu'`, torch should not detect any GPU on the machine for the selfplay, hence forcing dataparallel to be in cpu mode.

Are you sure that it is the selfplay that runs on your GPU ?
Can you post the precise error you are having ?

ps: MuZero and Ray on windows are experimental for now.

**Comment by yffbit** [comment]
I did a simple test. The RuntimeError is same.

> 
import torch
cuda, cpu = 'cuda', 'cpu'
model = torch.nn.Linear(20,5)
input = torch.randn(100,20)
model.to(cuda)
o1 = model(input.to(cuda))
model.to(cpu)
o2 = model(input.to(cpu))

model_parallel = torch.nn.DataParallel(model)
o3 = model_parallel(input)
o4 = model_parallel(input.to(cuda))
model_parallel.to(cpu)
o5 = model_parallel(input.to(cpu))
o6 = model_parallel.module(input)

> 
Traceback (most recent call last):
  File "D:/Python/torch_test1.py", line 14, in <module>
    o5 = model_parallel(input.to(cpu))
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 149, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

The error has nothing to do with Ray.

**Comment by werner-duvaud** [comment]
Normally I use Ray to prevent this error from happening.

It may be related to the first error which is due to the fact that you misconfigured the distribution of the GPU between the workers. Can you share your configuration to fix this problem and then check that you still have the second error?

**Comment by werner-duvaud** [comment]
Can you confirm me that this works for you too ?

```
import torch
import ray

ray.init()
cuda, cpu = 'cuda', 'cpu'
model = torch.nn.Linear(20,5)
input = torch.randn(100,20)
model.to(cuda)
o1 = model(input.to(cuda))
model.to(cpu)
o2 = model(input.to(cpu))
model_parallel = torch.nn.DataParallel(model)
o3 = model_parallel(input)
o4 = model_parallel(input.to(cuda))
model_parallel.to(cpu)

#just added this
@ray.remote(num_gpus=0)
def model_parallel_cpu(input):
	model_parallel = torch.nn.DataParallel(model).to(cpu)
	return model_parallel(input)
o5 = ray.get(model_parallel_cpu.remote(input.to(cpu)))

o6 = model_parallel.module(input)
```

**Comment by yffbit** [comment]
What do you mean about configuration? configuration for what? I use the raw code. Nothing has been modified. Have you done the simple test I post, it raises the similar error.

**Comment by werner-duvaud** [comment]
Ok sorry it was unclear, I was talking about the `MuZeroConfig` class in the game file in the games folder. What default game are you trying to train then ?
There is something strange because Ray requested more than 1 GPU but the default game configurations only need 1 GPU.

**Comment by yffbit** [comment]
> Here is how we can avoid it with Ray.
> Can you confirm me that this works for you too ?
> 
> ```
> import torch
> import ray
> 
> ray.init()
> cuda, cpu = 'cuda', 'cpu'
> model = torch.nn.Linear(20,5)
> input = torch.randn(100,20)
> model.to(cuda)
> o1 = model(input.to(cuda))
> model.to(cpu)
> o2 = model(input.to(cpu))
> model_parallel = torch.nn.DataParallel(model)
> o3 = model_parallel(input)
> o4 = model_parallel(input.to(cuda))
> model_parallel.to(cpu)
> 
> #just added this
> @ray.remote(num_gpus=0)
> def model_parallel_cpu(input):
> 	model_parallel = torch.nn.DataParallel(model).to(cpu)
> 	return model_parallel(input)
> o5 = ray.get(model_parallel_cpu.remote(input.to(cpu)))
> 
> o6 = model_parallel.module(input)
> ```

**Comment by yffbit** [comment]
> Here is how we can avoid it with Ray.
> Can you confirm me that this works for you too ?
> 
> ```
> import torch
> import ray
> 
> ray.init()
> cuda, cpu = 'cuda', 'cpu'
> model = torch.nn.Linear(20,5)
> input = torch.randn(100,20)
> model.to(cuda)
> o1 = model(input.to(cuda))
> model.to(cpu)
> o2 = model(input.to(cpu))
> model_parallel = torch.nn.DataParallel(model)
> o3 = model_parallel(input)
> o4 = model_parallel(input.to(cuda))
> model_parallel.to(cpu)
> 
> #just added this
> @ray.remote(num_gpus=0)
> def model_parallel_cpu(input):
> 	model_parallel = torch.nn.DataParallel(model).to(cpu)
> 	return model_parallel(input)
> o5 = ray.get(model_parallel_cpu.remote(input.to(cpu)))
> 
> o6 = model_parallel.module(input)
> ```

It doesn't work for me. The error is the same.
Traceback (most recent call last):
  File "D:/Python/torch_test2.py", line 22, in <module>
    o5 = ray.get(model_parallel_cpu.remote(input.to(cpu)))
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\ray\worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::__main__.model_parallel_cpu() (pid=4828, ip=192.168.43.250)
  File "python\ray\_raylet.pyx", line 446, in ray._raylet.execute_task
  File "D:/Python/torch_test2.py", line 21, in model_parallel_cpu
    return model_parallel(input)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 149, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

**Comment by werner-duvaud** [comment]
Ok so I think you get the error because Ray is still experimental on windows.
To confirm this, can you please run this:
```
import torch
import ray

ray.init()

@ray.remote(num_gpus=0)
def test():
    print(torch.cuda.is_available())

ray.get(test.remote())
```
It prints False for me. I suspect you will have True.

**Comment by yffbit** [comment]
> Ok so I think you get the error because Ray is still experimental on windows.
> To confirm this, can you please run this:
> 
> ```
> import torch
> import ray
> 
> ray.init()
> 
> @ray.remote(num_gpus=0)
> def test():
>     print(torch.cuda.is_available())
> 
> ray.get(test.remote())
> ```
> 
> It prints False for me. I suspect you will have True.

Yes. It print True. My Ray version is 0.8.6.

**Comment by werner-duvaud** [comment]
I'll wait until Ray is stable on windows to fix those kind of issues. You can still use Google Colab to run MuZero. (Also maybe putting every models on your gpu will make it run.)

https://github.com/ray-project/ray/issues/9114

**Comment by jefflomax** [comment]
This issue is linked from Ray, closing it leaves a false impression that it's works.  
How much work do we think it will be to just use PyTorch DataLoader and ditch Ray?

**Comment by werner-duvaud** [comment]
I don't know if hiding the GPU from PyTorch with num_gpus=0 is in Ray's specifications, so I wanted to wait for the stable version of Ray for windows before tackling it. 

Another solution in the meantime is to use WSL on Windows .

Concerning Dataloader I don't really understand the use here, we use ray for multi processing. For the moment I'm satisfied with Ray but a replacement could be torch.distributed if someone want to try.

**Comment by digits122** [comment]
I got this same issue, I don't think it's ray problem.

I've run this

```
import torch
cuda, cpu = 'cuda', 'cpu'
model = torch.nn.Linear(20,5)
input = torch.randn(100,20)
model.to(cuda)
o1 = model(input.to(cuda))
model.to(cpu)
o2 = model(input.to(cpu))
model_parallel = torch.nn.DataParallel(model)
o3 = model_parallel(input)
o4 = model_parallel(input.to(cuda))
model_parallel.to(cpu)
o5 = model_parallel(input.to(cpu))
o6 = model_parallel.module(input)
```

and it returns the same error as [yffbit](https://github.com/yffbit) mentioned.


o5 = model_parallel(input.to(cpu))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\torch\nn\parallel\data_parallel.py", line 153, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
