### ISSUE TITLE
Loading more than one replay buffer?

### ISSUE THREAD

**Issue by astronasko** [werner-duvaud/muzero-general#71]
Greetings,
Is there any possibility of loading more than one replay buffer before training? For the time being, the second loaded buffer overwrites the first.

**Comment by ahainaut** [comment]
Hi,

We haven’t planned to add this feature for now. But the replay buffer is a dictionnary saved with pickle, you can easily load the two replay buffers and merge them into one replay buffer.

**Comment by astronasko** [comment]
Good to hear, thank you!

**Comment by astronasko** [comment]
Sorry to bother again. I have used this bit of code to merge three .pkl files,
```py
import pickle

file = open('results/santorini/pickles/replays.pkl', 'ab')

with open('results/santorini/pickles/replay_buffer001.pkl', 'rb') as f:
    pickle.dump(pickle.load(f), file)
with open('results/santorini/pickles/replay_buffer002.pkl', 'rb') as f:
    pickle.dump(pickle.load(f), file)
with open('results/santorini/pickles/replay_buffer003.pkl', 'rb') as f:
    pickle.dump(pickle.load(f), file)
```
which did the job successfully. However, muzero loads the games of the first replay buffer only. I suspect this has to deal with common indices, shared between replay buffers. The loader might just load the elements with first unique indices.
Could you please recommend any solution?

**Comment by astronasko** [comment]
**Solution:**
The replay_buffer dict has integer indices - which makes it nothing more than a basic list. One can just load ``list()`` files from .pkl, concatenate them together, convert them to ``dict()`` again and save as .pkl .
```python
import pickle

out_list = list()

with open('results/santorini/pickles/replay_buffer001.pkl', 'rb') as f:
    d = pickle.load(f)
    out_list.extend( [v for k,v in d.items()] )
with open('results/santorini/pickles/replay_buffer002.pkl', 'rb') as f:
    d = pickle.load(f)
    out_list.extend( [v for k,v in d.items()] )
with open('results/santorini/pickles/replay_buffer003.pkl', 'rb') as f:
    d = pickle.load(f)
    out_list.extend( [v for k,v in d.items()] )

out_file = open('results/santorini/pickles/replays.pkl', 'wb')
pickle.dump(output, out_file)
out_file.close()
```
