### ISSUE TITLE
Reuse Search Tree

### ISSUE THREAD

**Issue by cfytrok** [werner-duvaud/muzero-general#72]
Is there a reason why on every step of selfplay gave muzero starts to build game tree from scratch?
We use the same networks throughout the game. So game subtree, that we build on second step should be the same, as subtree that was build on first step for child node. They differ only in the number of nodes.

**Comment by ahainaut** [comment]
Hi,

The two trees do not start from the same observations, the second tree is different because the information of the root contains the information of the new observation.

**Comment by cfytrok** [comment]
Thanks. You are right. Muzero predicts policy and value based on hiden state. There are 2 options to create hiden state: using representation network and observation; using dynamics network, previose hiden state and action.
So in the second step of the game root node hidden state (presentation network result) is different from the child node hidden state (dynamics network result) in the first step.
