### ISSUE TITLE
Unnecessary self-play after checkpoint load

### ISSUE THREAD

**Issue by astronasko** [werner-duvaud/muzero-general#75]
I was doing training on a custom game, with ``replay_buffer`` of 1000 and a ``ratio`` of 1.5. In my training session, about 1100 games were played, so some of the games had to be removed from the replay buffer, as expected.

However, when I loaded another training session, the algorithm began self-playing without training. I suspect it thought that 1000 games were present, so it tried to self-play 100 more again, so to reach the desired ratio. To my mind this is a bug, since 100 games are already in the buffer of the previous training session; thus this additional self-play is unnecessary.

Please correct me if I am wrong.

**Comment by astronasko** [comment]
**To the rest facing the same problem, a temporary fix:**
The model checkpoint file contains information about the number of played games. Since this integer is capped at ``replay_buffer``, as discussed above, it needs to be adjusted manually:
```py
import torch

with open('results/game/instance/model.checkpoint', 'rb') as f:
    d = torch.load(f)

d['num_played_games'] = 1100 # Adjust as you see fit
torch.save(d, 'results/game/instance/model_adjusted.checkpoint')
```
Then, the adjusted checkpoint must be imported from ``muzero.py``.

**Comment by werner-duvaud** [comment]
Hi,

You are right, thank you.
Should be fixed with the next commit.

**Comment by astronasko** [comment]
Thank you. Are old replay buffers / checkpoints still compatible? If not so, what needs to be adjusted?
