### ISSUE TITLE
Runtime Error: module must have its parameters and buffers on device

### ISSUE THREAD

**Issue by tslever** [werner-duvaud/muzero-general#78]
Dear Mr. Duvaud,

Upon cloning your repository to ".../Documents/AI", adding swig-4.0.2 (https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip/download?use_mirror=phoenixnap) to your repository and adding the swig directory to PATH, "running pip install -r requirements.txt", running "python muzero.py", entering "8" for tictactoe, and entering "0" for training, I encounter the following runtime errors. What do you suggest that I do?

Best regards,

Tom Lever

<img width="951" alt="Error" src="https://user-images.githubusercontent.com/46533664/92334749-d3d89500-f05e-11ea-9f20-edaed9df894f.PNG">

**Comment by werner-duvaud** [comment]
Hi,

You seem to be using MuZero on Windows. The error looks like this [one](https://github.com/werner-duvaud/muzero-general/issues/66).
For the moment MuZero is based on Ray which is not officially compatible with Windows.
To use MuZero you can use Google Colab or a virtual machine with Linux (until Ray is in stable version under Windows).


PS: Not tested workaround ideas below
* Maybe if you set in the configuration of MuZero `training_on_gpu`, `selfplay_on_gpu` and `reanalyse_on_gpu` to `True` you will be able to use MuZero with GPU on Windows.
* Maybe by setting your environment variable cuda_visible_devices to empty with `set cuda_visible_devices=` and then launching muzero.py you will be able to use MuZero but without GPU.

**Comment by tslever** [comment]
Mr. Duvaud,


Your suggestions of modifying "self.selfplay_on_gpu = False" to "self.selfplay_on_gpu = True", and "self.reanalyse_on_gpu = False" to "self.reanalyse_on_gpu = True", in class MuZeroConfig in tictactoe.py, allowed me to begin a game of tictactoe. Thank you. As written "self.train_on_gpu = True if torch.cuda_is_available()".

As you can see in the below screenshot, when I attempted to put a first "O" at (1, 3) in the tictactoe board, muzero.py reported that I had played an "O" at (3, 3). During my second move, I was unable to put an "O" at (1, 2), even though it was available. Additionally, MuZero's suggestion at the point would have caused me to loose the game, even though there is a weights file in ".../muzero-general/results/tictactoe/experiment1". Would either of these issues impact my ability to outline MuZero?


<img width="1913" alt="Working" src="https://user-images.githubusercontent.com/46533664/92349755-01e0c800-f0a5-11ea-9e9a-323bab6bfe31.PNG">

**Comment by werner-duvaud** [comment]
> Your suggestions of modifying "self.selfplay_on_gpu = False" to "self.selfplay_on_gpu = True", and "self.reanalyse_on_gpu = False" to "self.reanalyse_on_gpu = True", in class MuZeroConfig in tictactoe.py, allowed me to begin a game of tictactoe.

Great new !

You are right the played columns are no more correctly reported in Tic Tac Toe.
I fixed that in the last commit, sorry about that and thanks for reporting.

Now the board is as follow:
row 3
row 2
row 1
----->   col 1    col 2    col 3
