### ISSUE TITLE
play_game() game_history.action_history.append(0)

### ISSUE THREAD

**Issue by nnnet** [werner-duvaud/muzero-general#79]
May be change
game_history.action_history.append( numpy.random.choice(self.game.legal_actions()) )
?

**Comment by werner-duvaud** [comment]
I don't think so.
If you are talking about this line https://github.com/werner-duvaud/muzero-general/blob/07ef10203e6c175c371dab5f909bc4160581f611/self_play.py#L118 here we are appending a "fake action" which corresponds to the action taken before the reset just for the consistency of the game_history. This action does not correspond to the legal actions you are suggesting and it should'nt be used anywhere.
