### ISSUE TITLE
How easy would it be to implement a chess variant in MuZero?

### ISSUE THREAD

**Issue by fastelectronicvegetable** [werner-duvaud/muzero-general#82]

**Comment by werner-duvaud** [comment]
Hi,

If you're referring to the recent DeepMind paper on it, I think it's as easy as for AlphaZero. You just have to modify the rules of the chess engine used as an environment. The complicated part is the training which will require great computing power for each variant (they trained it from scratch for every variant).

**Comment by goshawk22** [comment]
I have a chess variant that is working but I'm still unsure on some of the configuration variables at the start of the game python files.
I also keep getting a lot of info messages about illegal losses and stuff.
I will get the code on GitHub for you to see.

**Comment by goshawk22** [comment]
See https://github.com/goshawk22/muzero-general

**Comment by werner-duvaud** [comment]
@goshawk22 For questions related to adding a custom game, please use the discord.
