### ISSUE TITLE
Ray: "ActorClass" has no attribute options

### ISSUE THREAD

**Issue by worldsoft** [werner-duvaud/muzero-general#84]
When starting the model, I get this error

**(muzero) bash-3.2$ python muzero.py
Traceback (most recent call last):
  File "muzero.py", line 10, in <module>
    import ray
  File "/Users/Administrator/anaconda3/envs/muzero/lib/python3.6/site-packages/ray/__init__.py", line 25, in <module>
    CDLL(so_path, ctypes.RTLD_GLOBAL)
  File "/Users/Administrator/anaconda3/envs/muzero/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/Administrator/anaconda3/envs/muzero/lib/python3.6/site-packages/ray/_raylet.so, 10): Symbol not found: _getentropy
  Referenced from: /Users/Administrator/anaconda3/envs/muzero/lib/python3.6/site-packages/ray/_raylet.so (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Administrator/anaconda3/envs/muzero/lib/python3.6/site-packages/ray/_raylet.so**

**Comment by goshawk22** [comment]
How did you install ray?

**Comment by worldsoft** [comment]
I have installed the latest version ray. I tried all versions, the game started when I installed version 0.6.0. But when I chose to train, I was given the following error: "ActorClass" has no attribute options"

**Comment by werner-duvaud** [comment]
Hi,
Looks like a Ray installation problem. Creating a new virtual environment and installing the dependencies works on Mac for me. If the problem persists you should check out Ray's documentation and issues.

**Comment by viniciusguigo** [comment]
Had a similar issue with the default version of ```ray``` it got installed first (0.7.1 for me). Updating ```ray``` to its latest version (currently, 1.1.0) with ```pip install --upgrade ray``` solves the problem.
