### ISSUE TITLE
Question: self.observation_shape

### ISSUE THREAD

**Issue by Z223I** [werner-duvaud/muzero-general#88]
Hello!
Could you please explain why Tic Tac Toe has
self.observation_shape = (3, 3, 3)
Why three channels?
Why is Connect 4
self.observation_shape = (3, 6, 7)
I am try to construct a game but I just don't understand how to determine that variable.
Thanks!!

Are the three channels RGB?

**Comment by werner-duvaud** [comment]
observation_shape corresponds to the dimensions of the observation array.

It must have 3 dimensions : channel, height, width.

In the case of atari, we have 3 images for red green and blue and these images each have the size of 96 pixels by 96 pixels.  If we stack them in a certain way we get an array of size 3 x 96 x 96. So observation_shape = (3, 96, 96).

For tic tac toe and connect4, it is very similar except that the images are in fact game boards (3x3 for tic tac toe and 6x7 for connect4). There is a plan for player 1's pawns (only zeros elsewhere), a plan for player 2's pawns and a final plan which is the size of a board as well but filled in with the current player's number.

For tic tac toe, the observation array returned by the game at each move is 
[3x3 array to indicate crosses on the board, 3x3 array to indicate circles on the board, 3x3 array fill with 1 if it's cross player turn else -1 if it's circle player turn]

**Comment by Z223I** [comment]
Thanks so much!!

**Comment by SunilaAkbar** [comment]
Hi,

First, thanks for the excellent code. 

I have a question that if number of channels is '1', that is, if we have 2 dimensional image of dimension (1, 8, 5), what will be the effect on ResNet configuration? 

Secondly, if my reward is having a negative real value of the range '0' to '1500+', what should be the support_size?

Your response will highly be appreciated.

**Comment by SunilaAkbar** [comment]
Hi, 

I am using MuZero for my Task Scheduling problem. I have been struggling with the right set of hyperparameters, spent almost two months now. Now, I want to experiment with the network.

I want to ask that if my observation size is (1, 8, 5), that is, the number of channels is '1' then what woud be the suitable ResNet configuration. 

Secondly, if my reward is of negative real values, ranging from '0' to apx. '-2000', then what should be the support_size. 

Thanks!
