### ISSUE TITLE
Observation format

### ISSUE THREAD

**Issue by KhangNguyen69** [werner-duvaud/muzero-general#91]
For tic tac toe, the observation array returned by the game at each move is
[3x3 array to indicate crosses on the board, 3x3 array to indicate circles on the board, 3x3 array fill with 1 if it's cross player turn else -1 if it's circle player turn]

Why do we need to return this format? If I want to customize for chess, what should I do?
Can the model work if I return the observation is the chessboard?

**Comment by werner-duvaud** [comment]
Hi,
If you want to take a look there is a pull request which adds chess. (not tested).
For how to encode a chess board, the Alpha Zero paper gives details. https://arxiv.org/abs/1712.01815
