### ISSUE TITLE
windows TypeError: render() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by mikelty** [werner-duvaud/muzero-general#98]
Thanks for open sourcing this repo but as I try running it on windows 10, the following happened: 
```
D:\tweak2\muzero-general>py37 muzero.py

Welcome to MuZero! Here's a list of games:
0. atari
1. breakout
2. cartpole
3. connect4
4. gomoku
5. gridworld
6. lunarlander
7. simple_grid
8. tictactoe
9. twentyone
Enter a number to choose the game: 6
2020-12-26 15:02:12,265 INFO services.py:1173 -- View the Ray dashboard at http://127.0.0.1:8265

0. Train
1. Load pretrained model
2. Diagnose model
3. Render some self play games
4. Play against MuZero
5. Test the game manually
6. Hyperparameter search
7. Exit
Enter a number to choose an action: (pid=61632) Windows fatal exception: access violation
(pid=61632)
2
Traceback (most recent call last):
  File "muzero.py", line 632, in <module>
    muzero.diagnose_model(30)
  File "muzero.py", line 457, in diagnose_model
    dm.compare_virtual_with_real_trajectories(obs, game, horizon)
  File "D:\tweak2\muzero-general\diagnose_model.py", line 104, in compare_virtual_with_real_trajectories
    self.plot_mcts(root, plot)
  File "D:\tweak2\muzero-general\diagnose_model.py", line 188, in plot_mcts
    graph.render("mcts", view=plot, cleanup=True, format="pdf")
TypeError: render() got an unexpected keyword argument 'format'```
I'm using python 3.7.0 cuda 10.1 (I suppose I haven't tested that too much) and pip.

**Comment by mikelty** [comment]
(I'm using python 3.7.0 cuda 10.1 (I suppose I haven't tested that too much) and pip.) the last line got into the code block.

**Comment by pongtep63** [comment]
If you re can't fixed the problem. I will cancel for everythings. Your team can't help me. And i don't want any game too. I am not risk man.  I am poor man... please understand. Thanks you for everythings you tired to help me. I am sorry i have no money in my Bank and no money on my credit cards too.

**Comment by pongtep63** [comment]
I am very sorry and apologize with your teams. I can't not speak English as well.  Thanks you very much for helping.

**Comment by pongtep63** [comment]
I need you to help about my blocks problem.  And i don't want any things about games. Please

**Comment by werner-duvaud** [comment]
@mikelty 
It doesn't seem to happen on Linux.
Have you installed the latest version of graphviz?
You have to install graphviz first: https://graphviz.org/download/ then `pip uninstall graphviz` and `pip install grapvhiz`
