### ISSUE TITLE
Cartpole performance very slow

### ISSUE THREAD

**Issue by jarlva** [werner-duvaud/muzero-general#99]
Hello, 

I just tried the colab notebook (copied from https://github.com/werner-duvaud/muzero-general/blob/master/notebook.ipynb). After 13 minutes it still got a low score (see below). Other frameworks complete after no more than 5 minutes. What am I doing wrong?

Made sure to select GPU. Link: https://colab.research.google.com/drive/1XF16Aqr7zZpp54rsSN3dj7NicDA4yTyM?usp=sharing 

![image](https://user-images.githubusercontent.com/26058035/103152238-c589c280-478e-11eb-835d-c1c83475f444.png)

**Comment by werner-duvaud** [comment]
Muzero is greedy in cpu, which can be limiting in colab, for cartpole you can set `use_last_model_value` to `False` to go faster. Also as muzero is model based with a lookahead search, it takes more time to train but it requires less interaction with the environment.
